# Use root/example as user/password credentials
version: '3.9'

services:
  # next-install:
  #   image: node:latest
  #   volumes:
  #     - ./frontend:/app
  #   working_dir: /app
  #   command: npm install

  # next:
  #   image: node:latest
  #   restart: always
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./frontend:/app
  #   working_dir: /app
  #   command: npm run dev

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  
  fastapi:
    image: python:3.11
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    working_dir: /app
    command: bash -c "pip install -r requirements-docker.txt && uvicorn main:app --reload --host 0.0.0.0"