version: '3.2'

services:
  next:
    image: node:slim
    restart: always
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: npm run build && npm run start

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  
  fastapi:
    image: python:3.11
    restart: always
    volumes:
      - ./backend:/app
    working_dir: /app
    command: bash -c "pip install -r requirements-docker.txt && uvicorn main:app --reload --host 0.0.0.0"
  
  nginx:
    image: nginx:1.21.4
    hostname: nginx
    restart: always
    volumes:
      - ./server/nginx/conf.d/production.conf:/etc/nginx/conf.d/default.conf
    environment:
      - VIRTUAL_HOST=sparkai.site,www.sparkai.site,api.sparkai.site
      - LETSENCRYPT_HOST=sparkai.site,www.sparkai.site,api.sparkai.site
    networks:
      - proxy_network
  
volumes:
  static: {}

networks:
  proxy_network:
    external: true